### ISSUE TITLE
[PM] Publish CI projection system contract

### ISSUE THREAD

**Issue by eng-cc** [eng-cc/oasis7#3882]
task_uid: task_ac8ffdf96bd149b0bc917aa9897f5a03

GitHub-backed oasis7 PM task.

Task metadata:
- owner_role: `repository_health_engineer`
- module: `engineering`
- status: `candidate`
- workflow_phase: `bootstrap`
- priority: `P2`
- worktree_hint: `/home/scc/worktrees/oasis7-engineering-ci-projection-system-contract-publication`
- loop_binding_b64: `eyJhY2NlcHRhbmNlX3JlZnMiOlsiSXNzdWUgIzM4NzYgY29kZS1sb29wIHRlY2huaWNhbCBpbnB1dCBibG9ja2VyIiwiUFIgIzM4NzIgbWVyZ2VkIENJIHByb2plY3Rpb24gZGVzaWduIGF1dGhvcml0eSIsImRvYy9lbmdpbmVlcmluZy93b3JrZmxvdy9sb2NhbC1jb2RleC10aHJlZS1sb29wLmRlc2lnbi5tZCM0LWNvbnRyYWN0cy1hbmQtZWZmZWN0aXZlLXBvbGljeSJdLCJib290c3RyYXBfZXBvY2giOjIsImNoYW5nZV9pZCI6ImNpLXByb2plY3Rpb24tcHVibGljYXRpb24tbGl2ZS1hY3RpdmF0aW9uIiwiZGVwZW5kZW5jaWVzIjpbXSwiaW5wdXRfY29udHJhY3RzIjpbXSwibG9vcCI6InN5c3RlbSIsIm1hbnVhbF9yZXF1ZXN0X3JlZiI6Imlzc3VlY29tbWVudC01NzYwMjg4OTM5Iiwib3V0X29mX3Njb3BlIjpbInNjcmlwdHMvKioiLCIuZ2l0aHViLyoqIiwiY3JhdGVzLyoqIiwidGhpcmRfcGFydHkvKioiXSwib3duZXJfcm9sZSI6InJlcG9zaXRvcnlfaGVhbHRoX2VuZ2luZWVyIiwicG9saWN5X2NvbW1pdCI6ImVlZWUyMjkwZmFjYTk1MmVlODE5MDAzZDhjMGQ5NzE0MmZmNGM0MjQiLCJwb2xpY3lfZGlnZXN0Ijoic2hhMjU2OjYyZjgwY2EyMWY2OTUyNjlmYWZiMGYxNzE2OTRlYjk0YzE5MzhhMDg5YmM4Y2YyNGYxYzRjZTY5OTE1MDc2NjAiLCJyZXF1ZXN0X2tleSI6ImNpLXByb2plY3Rpb24tc3lzdGVtLWNvbnRyYWN0LXB1YmxpY2F0aW9uLXYxIiwic2NoZW1hIjoib2FzaXM3Lmxvb3AtdGFzay92MSIsInRhcmdldF9kZWxpdmVyeSI6IlB1Ymxpc2ggYW5kIGxpdmUtcmVhZGJhY2sgdGhlIG1lcmdlZCBDSSBJbXBhY3QgUHJvamVjdGlvbiBzeXN0ZW0gY29udHJhY3QgZm9yIGNvZGUtbG9vcCBhZG1pc3Npb24iLCJ0YXNrX3VpZCI6InRhc2tfYWM4ZmZkZjk2YmQxNDliMGJjOTE3YWE5ODk3ZjVhMDMiLCJ3cml0ZV9zY29wZSI6WyJkb2MvZW5naW5lZXJpbmcvd29ya2Zsb3cvY2ktcHJvamVjdGlvbi1wdWJsaWNhdGlvbi5kZXNpZ24ubWQiXX0`
- bootstrap_base_oid: `ddbc5a7d081cffd0c17697397ee89fbd69a98cd6`

Source refs:
- `/home/scc/worktrees/oasis7-engineering-manual-three-loop-activation/.pm/scratch/task_e9669b276d454273af23e1d3baf446cd/system-contract-publication-binding.json`
- `doc/engineering/workflow/ci-projection-publication.design.md`

Acceptance:
- Publish the merged PR #3872 CI projection system contract from a bound system loop and verify exact server readback, admin authority, merged bytes and eligibility
- Return the frozen input contract reference required for a later code-loop pilot; make no repository implementation change

**Comment by eng-cc** [comment]
Immutable loop binding history; removing current metadata does not restore legacy admission.

**Comment by eng-cc** [comment]
Task UID: task_ac8ffdf96bd149b0bc917aa9897f5a03
Evidence Phase: start
Role: tpm
Recorded At: 2026-09-21T14:49:46+08:00

Workflow Phase: start
Task Status: candidate
Issue: https://github.com/eng-cc/oasis7/issues/3882
Worktree: /home/scc/worktrees/oasis7-engineering-ci-projection-system-contract-publication

**Comment by eng-cc** [comment]
Bootstrap recovery / route / Plan-Gap Evidence. UID task_ac8ffdf96bd149b0bc917aa9897f5a03; canonical worktree /home/scc/worktrees/oasis7-engineering-ci-projection-system-contract-publication; branch task/engineering-ci-projection-system-contract-publication; owner repository_health_engineer; frozen policy ddbc5a7d081cffd0c17697397ee89fbd69a98cd6. Initial stale-policy attempt created no task; retry hit uncertain GitHub API pagination and preserved worktree; exact resume-bootstrap created this Issue; workflow start and immutable snapshot were then completed. Snapshot .pm/scratch/task_ac8ffdf96bd149b0bc917aa9897f5a03/bootstrap-task-snapshot.json. Fresh doctor passed/no blockers. Route executing-project-tasks, bounded system contract publication; no repo implementation edits.

Step CP1: acceptance_refs Issue #3882 acceptance, #3876 blocker, PR #3872 approval; dependencies merged PR source fb102ac9ce6cb53eeed87fbe5504f901c21fd3b7 and merge 610988357fa3ba05ffb648a922c4f2a40d04f10b with identical design bytes sha256:789806a3ad373823dbbc2bc841748015fb35aba52d9131b0384a5d940550d255; verification_command professional contract review then trusted loop.py publish-contract and validate-contracts/live readback; verification_evidence exact publication ref/digest here and #3876; write_scope evidence/publication only, no repo diff; out_of_scope implementation/CI/crates/code task; required_role_slices repository_health_engineer contract validation and independent QA live readback.

Slice CP1-RH: role repository_health_engineer; type read-only contract candidate validation; intended inherit parent; actual inherited/unverified; minimal frozen packet; message-assigned fallback if named adapter unavailable; identity UID/worktree/policy above; governance AGENTS, role card, source manual transition, system-loop/execute skills; task truth #3882/#3876; user intent publish prerequisite contract; repo scope merged design, PR #3872, contract schema/candidate; boundary no writes/publication/next task; return pass/fail and exact corrections; sink #3882; TPM order 1. Slice CP1-QA follows publication: independent live publication/readback/eligibility validation, no edits, TPM order 2.

**Comment by eng-cc** [comment]
CP1-RH return / correction. Named-role dispatch failed 503; message-assigned repository_health_engineer fallback, adapter inactive/runtime unverified. Initial candidate FAIL, publication blocked before write. Exact findings: unresolved fragment `#7-状态事务与持久化` must retain punctuation as `#7-状态、事务与持久化`; contract scope uses exact target_delivery membership, so path globs alone do not cover downstream code admission. Candidate corrected only in activation scratch: recovery fragment now exact and scope now includes frozen downstream target_delivery `Validate the manual code-loop admission, scope enforcement and resume safety against immutable main without changing implementation`. Other checks passed: system ownership, #3882 identity, admin authority, PR #3872 merged source/merge identities, identical bytes sha256:789806..., all remaining fragments, and new_tasks/in_flight eligibility. Next: trusted publish-contract performs pre-write validation and live server readback.

**Comment by eng-cc** [comment]
{"contract":{"approval_ref":{"pr_number":3872,"repository":"eng-cc/oasis7"},"content_refs":[{"clauses":["CI-PROJECTION-BOUNDARY","CI-PROJECTION-FLOW","CI-PROJECTION-CONTRACTS","CI-PROJECTION-RECOVERY","CI-PROJECTION-COMPATIBILITY","CI-PROJECTION-VERIFICATION"],"fragments":{"CI-PROJECTION-BOUNDARY":"4-边界与结构","CI-PROJECTION-COMPATIBILITY":"10-兼容、迁移与回滚","CI-PROJECTION-CONTRACTS":"6-接口与数据合同","CI-PROJECTION-FLOW":"5-关键运行流程","CI-PROJECTION-RECOVERY":"7-状态、事务与持久化","CI-PROJECTION-VERIFICATION":"11-验证设计与可追溯性"},"path":"doc/engineering/workflow/ci-projection-publication.design.md","sha256":"sha256:789806a3ad373823dbbc2bc841748015fb35aba52d9131b0384a5d940550d255"}],"contract_id":"ci-impact-projection-publication-system","eligibility":{"in_flight":true,"new_tasks":true,"release":false},"merged_head":"610988357fa3ba05ffb648a922c4f2a40d04f10b","owner_loop":"system","revision":1,"schema":"oasis7.loop-contract/v1","scope":["Validate the manual code-loop admission, scope enforcement and resume safety against immutable main without changing implementation","scripts/pm/**",".github/workflows/**"],"source_head":"fb102ac9ce6cb53eeed87fbe5504f901c21fd3b7","upstream_contracts":[]},"contract_digest":"sha256:2e77d89a45e57871f8814b82b2a965bc10990e7321ffd06d7b4f209f06c7dacf","marker":"oasis7-loop-contract","task_uid":"task_ac8ffdf96bd149b0bc917aa9897f5a03"}

**Comment by eng-cc** [comment]
Publication recovery blocker / systematic-debugging route. Revision 1 was written as comment 5756654888, then post-write validation returned `contract does not cover target delivery`; recover now reports pending action publication:79acbd... and cannot reconcile because the immutable revision-1 scope omits this publisher task target_delivery. The contract is not accepted as usable evidence. Do not retry publication or mutate the comment. Root-cause hypothesis: publish_contract validates the publisher binding target only after remote write; pre-write validation should reject an unusable output (or recovery must have a canonical supersession path) before recording an unreconcilable action. #3882 remains fail-closed while a separate legacy compatibility repair task fixes trusted main and adds regression coverage.

**Comment by eng-cc** [comment]
## Bootstrap epoch 2 migration authorization

- Authorized by user in Codex task `01a0bf8a-90c7-7952-bd2d-71b664a8406e` on 2026-09-21.
- Authorized action: migrate this existing system-loop task to bootstrap epoch 2 using current trusted `main` policy authority, then run canonical `doctor`, `resume-check`, and journal `recover`.
- Task UID: `task_ac8ffdf96bd149b0bc917aa9897f5a03`
- Scope is unchanged. The immutable revision-1 publication must not be edited or manually marked reconciled.
- This authorization does not create or auto-start another loop task.

**Comment by eng-cc** [comment]
## Epoch 2 migration attempt and recovery blocker

- Authorization ref: issuecomment-5760288939.
- Proposed epoch-2 policy commit: `2df5a3d7456bd3c625bf9faac2e7783b797b9769`.
- `loop.py bind --migrate-epoch 2` failed closed before mutation: `unresolved action requires manual reconciliation before writer reuse`.
- Exact epoch-1 `loop.py recover` read back action `publication:79acbdc0a2ef7559d5963140c99a5e62570c9dc253f2b7e20a682481f6ada9e4` and retained `status=reconcile_required`; revision 1 cannot satisfy target-delivery coverage.
- No publication comment, journal entry, task binding, or repository source was manually mutated.

### Bounded professional slice

- role: `repository_health_engineer`
- slice type: recovery-contract analysis
- model configuration: adapter inactive on this surface; inherit current parent selection; actual runtime unverified
- context delivery: minimal task/head-bound packet
- identity and authority: Issue #3882, task `task_ac8ffdf96bd149b0bc917aa9897f5a03`, epoch-1 policy `ddbc5a7d...`, proposed epoch-2 policy `2df5a3d...`
- governance: AGENTS.md, source-of-truth recovery and manual transition contracts
- user intent: authorized epoch-2 migration and continued canonical recovery
- repo scope: `scripts/pm/loop_recovery.py`, `scripts/pm/loop_contracts.py`, related tests only
- collaboration boundary: analysis only; no writes or remote mutations
- return contract: root cause, smallest fail-closed recovery contract, required tests, compatibility risk
- integration owner: TPM
- integration order: analyze -> create separate legacy repair task if code change is required -> independent QA/review -> merge -> resume #3882

**Comment by eng-cc** [comment]
## Repository-health recovery-contract finding

- Slice outcome: `findings`.
- Adapter evidence: named role adapter returned 503; `adapter inactive on this surface`; message-assigned fallback used; runtime inherited, actual model/reasoning unverified.
- Finding: current `loop_recovery.reconcile` leaves a unique, exact, remotely present but deterministically invalid publication pending exactly like an uncertain write. Reservation then blocks the explicitly authorized epoch-2 migration.
- Required repair: a narrow explicit `supersede_invalid_publication` recovery disposition selected by exact action ID and current manual request ref. It may append reconciled evidence only for one exact publication whose task/repository/Issue/binding/action identity, full bytes, contract digest, authority and readback match, and whose sole stable validation blocker is target-delivery coverage. Any ambiguity, mismatch, API/read error, additional blocker or unknown classifier stays pending.
- Revision 1 remains immutable and ineligible; it must not be edited or deleted. A later valid publication must use revision 2.
- Implementation order: canonical source first, stable blocker code, recovery/facade plumbing, adversarial tests, independent QA/repository-health review, trusted CI, merge, then resume #3882 migration.
- Separate legacy repair task: required because #3882 cannot change or self-admit its epoch-1 workflow authority.

**Comment by eng-cc** [comment]
## Live supersession transition failure after PR #3889

- #3888 / PR #3889 merged as `3b383190916ac99123a2fc9cbc0d3a8ef0d9c516` and terminal cleanup completed.
- Authorized exact command used current merged `loop.py`, epoch-1 tool root, action `publication:79acbdc0a2ef7559d5963140c99a5e62570c9dc253f2b7e20a682481f6ada9e4`, and request ref `issuecomment-5760288939`.
- Failure before reconciliation write: `ImportError: cannot import name TARGET_DELIVERY_NOT_COVERED from loop_contracts`.
- Root signature: old-policy authority validation inserts epoch-1 `scripts/pm` into module resolution, so the new recovery facade imports the old contract module after admission.
- No publication comment, task binding, or journal resolution was mutated; action remains pending.
- Next step: bounded repository-health analysis and a separate legacy repair for mixed-epoch recovery module authority. No import-path override or manual journal edit is authorized.

**Comment by eng-cc** [comment]
## Mixed-epoch recovery analysis slice

- role: `repository_health_engineer`
- slice type: root-cause and authority-boundary analysis
- model/runtime: message-assigned fallback; adapter inactive on this surface; inherited runtime; actual runtime unverified
- identity/authority: #3882, task `task_ac8ffdf96bd149b0bc917aa9897f5a03`, old policy `ddbc5a7d...`, merged bridge `3b383190...`
- governance: AGENTS.md and canonical recovery/manual-transition contracts
- task truth: exact action remains pending after pre-write ImportError
- user intent: complete cleanup and subsequent recovery without bypasses
- repo scope: `scripts/pm/loop.py`, `loop_recovery.py`, module loading helpers and focused tests
- collaboration boundary: read-only analysis; no source/GitHub mutation
- return contract: smallest fail-closed module-authority fix, adversarial tests, compatibility risks, task requirement
- integration owner/order: TPM; analyze -> separate repair task -> QA/review/CI/merge -> resume #3882

**Comment by eng-cc** [comment]
## Repository-health mixed-epoch finding

- Verdict: blocking compatibility bug; failure is fail-closed and non-destructive.
- Root cause: epoch-1 `_trusted_module` installs old `loop_contracts` under the canonical module name; current `loop_recovery` then imports a symbol absent from that old module.
- Required design: explicitly pass the pinned epoch contract adapter into recovery; keep old module authority for remote readback/bytes/digest/provenance; keep stable blocker normalization in the current merged bridge; attest the bridge commit as clean, merged, and descendant of PR #3889.
- Legacy normalization may accept the untyped sole blocker only for exact policy `ddbc5a7d081cffd0c17697397ee89fbd69a98cd6` plus attested bridge. Any other policy, missing/dirty/unmerged bridge, mismatch, ambiguity, additional blocker or unreadable state remains pending.
- Supersession evidence must bind both old policy commit and current bridge commit/digest.
- Prohibited: PYTHONPATH/sys.modules hacks, substituting the new validator for old authority, or manual journal clearance.
- Separate GitHub-backed repair task and PR: required.
- Runtime: message-assigned repository-health fallback; adapter inactive; inherited runtime, actual model/reasoning unverified.

**Comment by eng-cc** [comment]
Immutable loop binding history; removing current metadata does not restore legacy admission.

**Comment by eng-cc** [comment]
{"contract":{"approval_ref":{"pr_number":3872,"repository":"eng-cc/oasis7"},"content_refs":[{"clauses":["CI-PROJECTION-BOUNDARY","CI-PROJECTION-FLOW","CI-PROJECTION-CONTRACTS","CI-PROJECTION-RECOVERY","CI-PROJECTION-COMPATIBILITY","CI-PROJECTION-VERIFICATION"],"fragments":{"CI-PROJECTION-BOUNDARY":"4-边界与结构","CI-PROJECTION-COMPATIBILITY":"10-兼容、迁移与回滚","CI-PROJECTION-CONTRACTS":"6-接口与数据合同","CI-PROJECTION-FLOW":"5-关键运行流程","CI-PROJECTION-RECOVERY":"7-状态、事务与持久化","CI-PROJECTION-VERIFICATION":"11-验证设计与可追溯性"},"path":"doc/engineering/workflow/ci-projection-publication.design.md","sha256":"sha256:789806a3ad373823dbbc2bc841748015fb35aba52d9131b0384a5d940550d255"}],"contract_id":"ci-impact-projection-publication-system","eligibility":{"in_flight":true,"new_tasks":true,"release":false},"merged_head":"610988357fa3ba05ffb648a922c4f2a40d04f10b","owner_loop":"system","revision":2,"schema":"oasis7.loop-contract/v1","scope":["Validate the manual code-loop admission, scope enforcement and resume safety against immutable main without changing implementation","Publish and live-readback the merged CI Impact Projection system contract for code-loop admission","scripts/pm/**",".github/workflows/**"],"source_head":"fb102ac9ce6cb53eeed87fbe5504f901c21fd3b7","upstream_contracts":[]},"contract_digest":"sha256:daa55a30ca78da58775d05c3753181a338f400b4f9d73651cd4329740837a8df","marker":"oasis7-loop-contract","task_uid":"task_ac8ffdf96bd149b0bc917aa9897f5a03"}

**Comment by eng-cc** [comment]
## Epoch-2 recovery and revision-2 publication complete\n\n- User authorization: `issuecomment-5760288939`\n- Repair bridge: merged PR #3893 at `eeee2290faca952ee819003d8c0d97142ff4c424`\n- Exact invalid publication supersession: `publication:79acbdc0a2ef7559d5963140c99a5e62570c9dc253f2b7e20a682481f6ada9e4`\n- Binding migrated to bootstrap epoch 2; old revision 1 remained immutable/ineligible.\n- `doctor`, `resume-check`, and `validate-contracts`: passed.\n- Revision 2 publication/readback: comment `5764009731`; digest `sha256:daa55a30ca78da58775d05c3753181a338f400b4f9d73651cd4329740837a8df`; six contract clauses read back successfully.\n- No manual journal/publication edits or generic force clear used.

**Comment by eng-cc** [comment]
Revision-2 contract publication and live readback completed under authorized epoch-2 migration. Publication comment: 5764009731; validation passed; old revision 1 remains immutable/ineligible. Task terminal cleanup is complete.
